- addon/utils/bind-data-test-attributes.js
- tests/unit/utils/bind-data-test-attributes-test.js
> Add warning when tagName is empty and data-test-* attributes are used

- package.json
> GreenKeeper: Ignore "babel-core" updates

- .npmignore
- .travis.yml
- ember-cli-build.js
- package.json
- testem.js
This updates ember-cli and other dependencies to their latest versions.
> update ember-cli and other libraries

- package.json
Add broccoli-stew to dependencies in package.json.
> Explicit dependency broccoli-stew

- README.md
I made you a poster, what do you think? :D
We're starting to do this for our addon videos
> Add video poster to README

- .bowerrc
- .travis.yml
- bower.json
- config/targets.js
- package.json
- tests/test-helper.js
> Update "ember-cli" to v2.13.0

- CHANGELOG.md
- package.json
- yarn.lock
generated using `yarn changelog --tag-from=ae44113`
> Generate CHANGELOG using `lerna-changelog`

- addon/utils/bind-data-test-attributes.js
- package.json
- yarn.lock
> chore(package): update ember-source to version 3.0.0

- index.html
> Mobile scrolling fixed

- .travis.yml
- config/ember-try.js
maybe this will fix our CI?
Includes and closes #247 
**Update:** it does! 🎉
> CI: Split CI tasks into multiple jobs

- node-tests/fixtures/default/expected.js
- node-tests/fixtures/default/expected6.js
- node-tests/fixtures/default/expected7.js
- node-tests/fixtures/default/fixture.js
- strip-data-test-properties-plugin.js
- strip-data-test-properties-plugin6.js
Make sure we only strip `data-test-*` selectors, and not `*data-test-*` selectors
> Only strip attribute *starting* with `data-test-`

- tests/acceptance/bind-data-test-attributes-in-components-test.js
- tests/dummy/app/templates/bind-test.hbs
Resolves https://github.com/simplabs/ember-test-selectors/issues/314
> tests: Check that `link-to` bindings work properly

- ember-cli-build.js
- index.js
Resolves https://github.com/simplabs/ember-test-selectors/issues/334
> Enable parallel file processing for `ember-cli-babel`

- README.md
> README: Add Node.js compatibility information

- .gitignore
- package.json
- yarn.lock
... because it's essentially deprecated
> Remove `ember-cli-eslint` dependency

- .github/workflows/release.yml
https://github.com/actions/setup-node isn't exactly clear on how this should be set up, but I guess maybe the registry definition was missing? we'll see... 😅
> CI: Fix `release` workflow

- README.md
- package.json
see https://github.com/simplabs/ember-test-selectors/pull/527 😅
> Update Node.js and Ember.js support documentation

- transform-test-selector-params-to-hash-pairs.js
> Deprecate `TransformTestSelectorParamsToHashPairs` transform

- README.md
Resolves https://github.com/simplabs/ember-test-selectors/issues/515
> README: Remove outdated EmberMap video

- package.json
- pnpm-lock.yaml
These are required for Ember.js v4 compatibility
> Add `ember-auto-import` and `webpack` dev dependencies

- .github/workflows/ci.yml
- config/ember-try.js
- ember-cli-build.js
- package.json
- pnpm-lock.yaml
Test against embroider during CI
> Add Embroider's test-setup package

- renovate.json
see https://github.com/simplabs/qunit-dom/blob/f535016e4040def80d4a7a8ae5ecee8a3b0bd77f/renovate.json#L7-L14
> renovate: Update `pnpm` version automatically

- index.js
Builds on #1212.
Closes #1211.
> Add support for `ember-cli-babel` v8

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
see https://nodejs.org/en/about/previous-releases 😉
> Remove support for Node.js 12, 14 and 16
