mainmatter/ember-test-selectors

index.js
The property that holds the environment name is actually `env`, not `environment`.
=> Fix env based activation

README.md, tests/integration/strip-data-test-attributes-test.js
…as they are much shorter and usually the version with a value is not needed.
=> use shorthand data attributes

README.md, test-support/helpers/ember-test-selectors.js, tests/unit/test-support/helpers-test.js
Hey – thanks for the great addon!
I took a look at #8. The solution is very similar but not exactly as suggested in the last comment
- The helper converts to `[data-test-selector]` not `*[data-test-selector]`
- The helper usage is also `testSelector('post-title')` not `testSelector('data-test-post-title')` as in the last comment (but I think that was your original intention anyhow)
I also removed the `StripTestSelectorsTransform` from ember-cli-build so the tests would have the selectors.
I based the readme additions off ember-simple-auth test helper section.
I'd be happy to make any changes :)
=> Add test helpers

CHANGELOG.md, README.md, index.js
For example, removing the test selectors in a staging or other pre-production environment.
=> Add ability to specify envs to strip selectors.

test-support/helpers/ember-test-selectors.js, tests/unit/test-support/helpers-test.js
Fixes #23 by using `Ember.isNone()` instead of falsiness on the second argument to the helper.
=> Check `value` argument for absence, not falsiness.

test-support/helpers/ember-test-selectors.js
Ternary operators are often considered harder to read, but in this case I think it simplifies the logic quite a bit.
=> Simplify testSelector() function

.travis.yml, config/ember-try.js
This was an unintended change in #29
=> CI: Run tests for all minor Ember versions again

.travis.yml, package.json, test/jshint.spec.js
This PR removes `mocha-jshint` and `ember-cli-jshint` in favor of calling `jshint` directly from the command line.
- `mocha-jshint` has no advantages unless the project has other tests that also use Mocha
- `ember-cli-jshint` is most important for linting the `app` and `addon` folder, that this project doesn't have
In the future we should probably also transition to ESLint instead.
=> Use "jshint" directly for linting

config/ember-try.js, ember-cli-build.js, package.json, tests/dummy/config/environment.js, tests/integration/strip-data-test-attributes-test.js
This introduces a `STRIP_TEST_SELECTORS` environment variables, which, if set, will enable test selector stripping for the `test` environment too. This allows us to test scenarios with and without test selector stripping without having to use `ember new` to initialize a second app (like ember-cli-addon-tests does).
=> Run tests with and without stripping test selectors

.travis.yml, config/ember-try.js, package.json
TravisCI will still test all scenarios, but locally a quick `npm test` will actually be quick now, while `npm run test:all` will kick off the test run that tests against all scenarios.
=> Change "npm test" to only run tests for current ember-try scenario

ember-cli-build.js, index.js
=> Introduce "strip" and deprecate "environments" option

addon/.eslintrc.js, addon/initializers/ember-test-selectors.js, addon/utils/bind-data-test-attributes.js, app/.eslintrc.js, app/initializers/ember-test-selectors.js, index.js, package.json, tests/acceptance/bind-data-test-attributes-in-components-test.js, tests/dummy/app/router.js, tests/dummy/app/templates/bind-test.hbs, tests/unit/utils/bind-data-test-attributes-test.js
This is the follow-up PR for #26.
Instead of automatically inserting `data-test-*` attributes for all components with the component's internal name as a value we're now simply auto-binding all `data-test-*` attributes that are present on a component.
=> Auto bind component data-test-* attributes

README.md, addon/index.js, test-support/helpers/ember-test-selectors.js, tests/unit/test-selector-test.js
```js
import testSelector from 'ember-test-selectors';
```
instead of
```js
import testSelector from '<app-name>/tests/helpers/ember-test-selectors';
```
The old import still works, but displays a deprecation warning. Due to the fact that our `addon` and `app` folders are only packaged in testing mode we don't have to worry about including testing code in the production build.
=> Simplify testSelector() import

index.js
The selectors should obviously only be stripped when there are no tests...! 🙈
=> Fix default setting for "strip" option

.travis.yml, index.js, node-tests/.eslintignore, node-tests/.eslintrc.js, node-tests/fixtures/default/expected.js, node-tests/fixtures/default/fixture.js, node-tests/strip-data-test-properties-plugin-test.js, package.json, strip-data-test-properties-plugin.js
This plugin will be added automatically to the Babel configuration of the host app and removes all `data-test-*` properties that it finds in JS code.
=> Add Babel 5 plugin stripping "data-test-*" properties

README.md, test-support/helpers/ember-test-selectors.js
[Rendered](https://github.com/Turbo87/ember-test-selectors/tree/readme#ember-test-selectors)
=> Updated and simplified README file

README.md, blueprints/.eslintrc.js, blueprints/files/tests/helpers/test-selectors.js, blueprints/index.js
Borrowing from an approach used by [ember-cli-flash](https://github.com/poteto/ember-cli-flash), we add a helper to duplicate the behavior of the initializer when we're running an integration test (where initializers are not loaded). Also, add a blueprint that auto-installs this helper and loads it in `tests/test-helepr.js`.
I haven't actually run the blueprint itself, but I did manually make the changes it would make on my own app and that fixed the issue I was having.
Hopefully this does the trick!
Fixes #49.
=> add blueprint + test helper for integration tests

tests/integration/strip-data-test-attributes-from-tags-test.js
This broke our tests for the `ember-canary` scenario
=> tests: Fix typo

index.js, tests/acceptance/bind-data-test-attributes-in-components-test.js, tests/dummy/app/templates/bind-test.hbs, transform-test-selector-params-to-hash-pairs.js
This PR is essentially #55 with a small change that restores Ember 1.13 compatibility.
=> Add support for component data-test-* attributes without values

addon/utils/bind-data-test-attributes.js
As noted in the Ember v2.11 release notes, concatenated properties such as attributeBindings are frozen in debug builds. This means we cannot push directly onto the attributeBindings array without first copying it via slice.
Without this change, users may see errors like this when the `attributeBindings.push()` call is made:
```
Uncaught TypeError: Can't add property 2, object is not extensible
```
References:
* http://emberjs.com/blog/2017/01/23/ember-2-11-released.html#toc_other-notable-changes
* https://github.com/emberjs/ember.js/pull/14389
* https://github.com/emberjs/ember.js/issues/14601
=> attributeBindings is now frozen in debug builds on v2.11, slice it before pushing

tests/dummy/app/components/data-test-component.js
This is the corresponding test case for #59 
/cc @bgentry
=> dummy/components: Explicitly set attributeBindings to [] to test freezing

.eslintrc.js, package.json
see https://github.com/simplabs/eslint-config-simplabs
=> Import ESLint config from eslint-config-simplabs

.gitignore, index.js, node-tests/fixtures/default/expected6.js, node-tests/multidep.json, node-tests/strip-data-test-properties-plugin-test.js, package.json, strip-data-test-properties-plugin6.js
=> Add Babel 6 compatibility

strip-test-selectors.js, tests/dummy/app/components/print-test-attributes.js, tests/dummy/app/templates/components/print-test-attributes.hbs, tests/integration/strip-data-test-attributes-from-components-test.js
Fixes use case like:
`{{my-component "param1" data-test-something}}`
Real world example:
`{{#link-to 'route' data-test-link}}Link{{/link-to}}`
This would fail on production build by being completely broken link, because link-to actually would receive` 'route' undefined` as input. As second argument is meant to be "model" on link-to, then this causes major problems.
Sorry for the package.json showing up in diff, rebased went a bit into woods.
=> fix: strip data-test-* attributes without explicit value from production build

index.js
=> Fix ember-cli-babel@6 compatibility

index.js
Resolves #95
/cc @lukemelia @rwjblue
=> Disable forced test selector stripping in addon templates

index.js
This appears to resolve https://github.com/simplabs/ember-test-selectors/issues/118
/cc @rwjblue
=> Add cacheKey() methods to template transforms

addon/utils/bind-data-test-attributes.js, package.json, tests/unit/utils/bind-data-test-attributes-test.js
see https://github.com/ember-cli/ember-rfc176-data
=> Use new module imports

index.js
`this` obviously referred to the addon itself and this only worked before because `ember-test-selectors` itself does not depend on `ember-cli-babel`. Using `this.parent` instead will check the `ember-cli-babel` version of the parent (either addon or app) which is the correct behavior, even for using it as a nested addon.
Resolves #130 
/cc @rwjblue
=> Fix Babel version detection

README.md, addon/index.js
This deprecates the `testSelector` helper and propagates using the respective attribute selectors directly instead. Besides obfuscating what's going on, the `testSelector` helper doesn't really do much.
=> Deprecate testSelector() helper

index.js
Closes #137.
Is this possible/sane to test? Or is this good enough?
=> use host to app.import

README.md, addon/index.js
Hi folks, I wrote up a codemod to help address the testSelector deprecation introduced in https://github.com/simplabs/ember-test-selectors/pull/134.
The codemod is here: https://github.com/lorcan/test-selectors-codemod
I thought it might be helpful to add a link to the codemod to the deprecation warning in the hopes that it makes it a little easier to fix :-)
=> Added a link to the deprecations warning to point to a codemod to help address it

tests/acceptance/bind-data-test-attributes-in-components-test.js, tests/dummy/app/templates/bind-test.hbs
…we didn't actually have an acceptance test for this previously which is why the changes in #150 don't break the build while they actually should.
=> add acceptance test for params-to-hash-pairs transform

index.js, package.json, tests/acceptance/bind-data-test-attributes-in-components-test.js, tests/dummy/app/controllers/bind-test.js, tests/dummy/app/templates/bind-test.hbs, yarn.lock
Followup to #149, this disables all handlebars transforms in pre-1.13 Ember. The transforms break otherwise, so this is a way to allow users to still get the benefits of test selectors, even if they won't be stripped.
=> bugfix(transform): Disable handlebars transform pre-Ember-1.13

tests/integration/strip-data-test-attributes-from-components-test.js, yarn.lock
This should bring us closer to a `master` that is 🍏  again.
This is a temporary measure until we implement #151, for which we should have a deprecation, for which CI needs to be 🍏  again.
=> Skip positional params stripping tests on Ember versions without reliable support

.travis.yml, testem.js
This switches from PhantomJS to Headless Chrome on CI and unblocks #161 which fails as Ember 3.0 which is now canary does not run with Phantom anymore.
=> use headless chrome on ci

package.json, tests/acceptance/bind-data-test-attributes-in-components-test.js, tests/dummy/app/version-checks.js, tests/integration/strip-data-test-attributes-from-components-test.js, tests/integration/strip-data-test-attributes-from-tags-test.js, yarn.lock
because it's obviously awesome! :D
=> Use `qunit-dom` assertions

package.json
This is only needed when we're testing ourself
=> Convert `broccoli-stew` to dev dependency

addon/index.js, test-support/helpers/ember-test-selectors.js, tests/dummy/app/components/data-test-component.js, tests/dummy/app/components/print-test-attributes.js, tests/dummy/app/controllers/bind-test.js, tests/helpers/destroy-app.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, tests/integration/strip-data-test-attributes-from-components-test.js, yarn.lock
Converts to using modules using `ember-modules-codemod`.
=> Converting imports to use ember modules

package.json, yarn.lock
This is handled by `ember-cli-babel` by now...
=> Remove unused `ember-cli-shims` dependency

addon/utils/bind-data-test-attributes.js, tests/unit/utils/bind-data-test-attributes-test.js
This is similar to https://github.com/simplabs/ember-test-selectors/pull/205 and makes the warnings/error more consistent.
I'm marking this as a breaking change because it might cause previously succeeding builds to fail now. If the component has no `data-test-` properties everything should still work fine though.
=> Use `assert()` for "read-only attributeBindings" warning

.travis.yml, package.json
Node 4 ist EOL and Node 6 will follow at the end of the month. Since we have several other breaking changes queued up, I think it is time to drop support for these old Node releases.
=> Drop support for Node.js 4 and 6

README.md, index.js
In Ember CLI 2.14 the `setupPreprocessorRegistry()` hook gained access to `this.app`, which means we can finally register our AST plugin properly
This should be considered a breaking change as it raises the minimum Ember CLI version to 2.14.
Resolves #333
=> Use `setupPreprocessorRegistry()` hook to register HTMLBars AST plugin

README.md, addon/utils/bind-data-test-attributes.js, node-tests/fixtures/default/expected.js, node-tests/fixtures/default/expected6.js, node-tests/fixtures/default/expected7.js, node-tests/fixtures/default/fixture.js, strip-data-test-properties-plugin.js, strip-data-test-properties-plugin6.js, tests/acceptance/bind-data-test-attributes-in-components-test.js, tests/dummy/app/components/tagless-component.js, tests/dummy/app/templates/bind-test.hbs, tests/dummy/app/templates/components/tagless-component.hbs, tests/unit/utils/bind-data-test-attributes-test.js
This is an extension to existing PR https://github.com/simplabs/ember-test-selectors/pull/291 which handles addition of attribute `supportsDataTestProperties`
I tried using the PR but it throws an exception `You cannot use `attributeBindings` on a tag-less component` while running following code:
```
component.set('attributeBindings', attributeBindings);
```
as the attribute bindings can not be set on component with empty `tagName`
This PR just adds an early exit in util `bind-data-test-attributes` in case of tag-less component and an acceptance test on top of existing PR https://github.com/simplabs/ember-test-selectors/pull/291
Resolves #290, Closes #291
=> Handle components with empty tag name

README.md, package.json
This should significantly speed up our CI times and users on older Ember versions can still use older releases of this addon
=> Adjust Ember.js support range to 2.16+

.npmignore
There is no need for us to ship the `yarn.lock` file to any users. I wish npm would just ignore this file by default...
IDE stuff is unfortunately necessary because npm does not have support for a global `.npmignore` like git.
=> Adjust `.npmignore` blacklist

index.js, package.json
Without this, each add-on which includes this add-on will rebuild the tree.
=> ensure custom tree is still memoized

index.js
This reverts PR https://github.com/simplabs/ember-test-selectors/pull/338 to fix https://github.com/simplabs/ember-test-selectors/issues/345
It turns out that https://github.com/ember-cli/ember-cli/pull/7059 does not quite work for us in addon builds as we still don't have access to the `EmberApp` instance in that case. We will look into fixing this in CLI itself, but in the meantime, reverting this should fix the immediate issue and enable us to take advantage of the Babel/HBS parallelization.
I've tested this variant in a production app and a fresh `ember addon` and it seems to do the right thing in both cases, for both dev and prod builds.
/cc @rwjblue
=> Revert "Use `setupPreprocessorRegistry()` hook to register HTMLBars AST plugin"

README.md
Splattributes make it a lot easier to work with test selectors for tagless components!
=> Add description of using splattributes for tagless components to README

package.json, yarn.lock
This requires Ember CLI 2.13+, but since we already have that as a requirement this does not need to be considered a breaking change... 🎉
=> Update `ember-cli-babel` to v7.12.0

README.md
Resolves #440 and updates the README for the Ember Octane world
=> Simplify and modernize README file

testem.js
... for GitHub Actions 😕
This will hopefully resolve the timeouts we've been seeing occasionally.
=> testem: Increase `browser_start_timeout`

.github/workflows/ci.yml, package.json
Node 8 is no longer supported by the Node developers, so we should drop support too. This will unblock a few of the open dependency upgrade PRs.
=> Drop support for Node 8

package.json
mostly to cut down our CI time... 😅
=> Drop support for Ember releases before v3.0.0

package.json
Prior to this, the `registry.add('htmlbars-ast-plugin', ...)` invocation in `index.js` runs _after_ all of the `htmlbars-ast-plugins` are read and registered for inline JS/TS compilation. It is still before stand alone templates are ran (and that is why it works for `*.hbs` files that are not colocation).
This ensures that `ember-test-selectors` runs _before_ `ember-cli-htmlbars` / `ember-cli-htmlbars-inline-precompile (so that we can ensure that `ember-test-selectors` included runs, and therefore the `htmlbars-ast-plugin` is registered before it is needed for inline template compilation).
Fixes #427
=> Ensure test selector stripping works for inline template compilation and co-located components

addon/utils/bind-data-test-attributes.js
see http://emberjs.github.io/rfcs/0554-deprecate-getwithdefault.html
=> bind-data-test-attributes: Avoid deprecated `getWithDefault()` call

strip-test-selectors.js
This PR addresses https://github.com/emberjs/ember.js/pull/19429 and should hopefully fix https://github.com/simplabs/ember-test-selectors/issues/671.
In other words, this should fix the deprecation message that started popping up on Ember v3.27.
=> Convert class based template compilation plugin to functional style

tests/dummy/app/templates/components/print-test-attributes.hbs
... to fix the corresponding deprecation warnings
=> dummy: Add missing `this.` prefixes

addon/utils/bind-data-test-attributes.js
https://github.com/simplabs/ember-test-selectors/issues/709 leaves us basically no other choice but to deprecate this functionality. Since Classic components in Ember and the curly invocation syntax are essentially deprecated and many apps have moved on to using Angle Bracket syntax this functionality is not really needed anymore and removing it should not break too many apps.
=> Deprecate automatic attribute bindings

index.js
To opt-in to address https://github.com/simplabs/ember-test-selectors/issues/709 until a breaking release is made.
This would allow you to specify:
```js
let app = new EmberAddon(defaults, {
'ember-test-selectors': {
patchClassicComponent: false
}
});
```
To avoid including the patch at all, thus avoid the deprecations if you do not use classic components (or the bindings on classic components, at least).
=> Add `patchClassicComponent` option to avoid deprecation warnings

transform-test-selector-params-to-hash-pairs.js
ember-source 3.27+: Using class based template compilation plugins is deprecated, please update to the functional style
=> Resolve class based transform deprecation

index.js, strip-test-selectors.js, transform-test-selector-params-to-hash-pairs.js
Prior to this change, you would receive the following warnings during an Embroider build:
```
broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `function(env) {
let b = env.syntax.builders;
let transform = (node) => {
if ('sexpr' in node) {
node = node.sexpr;
}
let testSelectorParams = [];
let otherParams = [];
node.params.forEach(function(param) {
if (isTestSelectorParam(param)) {
testSelectorParams.push(param);
} else {
otherParams.push(param);
}
});
node.params = otherParams;
testSelectorParams.forEach(function(param) {
let pair = b.pair(param.original, b.boolean(true));
node.hash.pairs.push(pair);
});
};
return {
name: 'TransformTestSelectorParamsToHashPairs',
visitor: {
MustacheStatement: transform,
BlockStatement: transform, …
```
=> Fix caching warnings when running under Embroider

index.js
Even ember-cli-babel v6.x is not officially supported anymore by the ember-cli team, so dropping support for ember-cli-babel v5.x should be uncontroversial. Dropping support will allow us to simplify our testing setup quite a bit.
=> Deprecate ember-cli-babel v5.x support

package.json
We're using https://github.com/renovatebot/renovate these days :)
=> Remove obsolete `greenkeeper` configuration

package.json
Using the addon with these Ember versions most likely still continues to work, but since we're dropping support I'm marking this as a breaking change too.
=> Stop testing on non-LTS Ember releases before v3.24

.github/workflows/ci.yml, .github/workflows/release.yml, package.json
Node.js 10 is no longer being maintained. see https://nodejs.org/en/about/releases/
=> Drop support for Node.js 10

.github/workflows/ci.yml
Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾
=> CI: Use new yarn cache in `setup-node` action

CHANGELOG.md, LICENSE, README.md, package.json
This changes all mentions of simplabs to Mainmatter and updates links to point to the new GitHub org.
=> rebrand simplabs to Mainmatter

.github/workflows/ci.yml
The latest versions appear to be breaking our CI runs for some reason. We can investigate this once we've managed to bring the other dependencies up-to-date.
=> CI: Disable floating Ember.js test scenarios

strip-test-selectors.js
Accessing this value in original is deprecated, and very noisily so, replacing this with value as recommended.
Deprecation Message:
`DEPRECATION: The original property on literal nodes is deprecated, use value instead`
Fixes #1219
=> Remove Glimmer AST Deprecation
